### ISSUE TITLE
Добавить выбор объектов

### ISSUE THREAD

**Issue by muxus-fd** [sergrt/CameraAiDetector#9]
Привет, если есть возможность выбрать отправку обнаружение только людей или инва машин .
И было бы супер в конфиге выбрать нужна раскадровка или нет.

**Comment by nitsir** [comment]
Если автор ореагирует, то хотелось бы ещё команду для телеграм бота "пауза" или даже пауза с указанием таймаута, полезно, когда чистишь снег или дети гуляют, сервер напрягается и бот забивает уведомлениями.
Но если нет, то нет, в любом случае спасибо за решение!

**Comment by muxus-fd** [comment]
я думаю настройка интервала - в какой период присылать видео. Раз в 5-10 минут .

> Если автор ореагирует, то хотелось бы ещё команду для телеграм бота "пауза" или даже пауза с указанием таймаута, полезно, когда чистыш снег или дети гуляют, сервер напрягается и бот забивает уведомлениями.Но если нет, то нет, в любом случае спасибо за решение!

**Comment by sergrt** [comment]
> Привет, если есть возможность выбрать отправку обнаружение только людей или инва машин .

С Codeproject AI не так очевидно, как это по-простому сделать. А для OpenCV вполне можно сделать загружаемый список из внешнего файла

> И было бы супер в конфиге выбрать нужна раскадровка или нет.

Это можно настроить опцией `send_video_previews`

> Если автор ореагирует, то хотелось бы ещё команду для телеграм бота "пауза" или даже пауза с указанием таймаута, полезно, когда чистишь снег или дети гуляют, сервер напрягается и бот забивает уведомлениями.

Тоже думал об этом, есть в планах.

**Comment by nitsir** [comment]
А можете сборку сделать под винду? Спасибо!

**Comment by sergrt** [comment]
Попробовал список объектов с OpenCV. Нейросеть работает таким образом, что начинает детектировать другие объекты. То есть, например, исключаем `car`. Нейросеть в том же месте начинает детектить `bottle`. Так что подобное усовершенствование пока кажется не очень рабочим. Если появятся варианты - вернусь к этому вопросу.

**Comment by sergrt** [comment]
Добавил команды `/pause <time>` / `/resume` для приостановки и возобновления обновлений. Изменения доступны по тегу `v0.0.8`, бинарные файлы залиты в секцию `Releases`
